// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDELiLYtqgjpGBSRthOlEVAOJhST0JGaDI',
    appId: '1:806908407307:web:ad5ae41416fc1406d4610e',
    messagingSenderId: '806908407307',
    projectId: 'msngu-1afad',
    authDomain: 'msngu-1afad.firebaseapp.com',
    storageBucket: 'msngu-1afad.appspot.com',
    measurementId: 'G-JM04RYKF2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9sWln-sFG3PHwiunRdmPVreJZ6DsWL2I',
    appId: '1:806908407307:android:2a81edd2457c3c64d4610e',
    messagingSenderId: '806908407307',
    projectId: 'msngu-1afad',
    storageBucket: 'msngu-1afad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuFaetIBK1gVG5nRSvIQK8kg_8mfDM96w',
    appId: '1:806908407307:ios:83803516423a45fed4610e',
    messagingSenderId: '806908407307',
    projectId: 'msngu-1afad',
    storageBucket: 'msngu-1afad.appspot.com',
    iosClientId: '806908407307-gtj8o2kdk29vigd7v8lkahv7ipku24i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.betamsngu',
  );
}
